controllers:
    resource: ../src/Dashboard/Controller/
    type: attribute

security_controllers:
    resource: ../src/Security/Controller/
    type: attribute

product_controllers:
    resource: ../src/Product/Controller/
    type: attribute
